# This is a basic workflow to help you get started with Actions

name: CI

# on: [push, pull_request]


jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout actions
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: Test Python Application
        run: |
          python --version
          pip install -r requirements.txt
